version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - /opt/odoo/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
        - default

  odoo:
    image: odoo:17
    volumes:
      - /opt/odoo/oca_modules:/mnt/extra-addons  #  OCA
      - /opt/odoo/custom_modules:/mnt/extra-addons  # módulos personalizados
      - /opt/odoo/config/odoo.conf:/etc/odoo/odoo.conf  # Archivo de configuración
    ports:
      - "8069:8069"
    depends_on:
      - db
    networks:
      - default
