version: '3'

services:
  odoo:
    image: odoo:17
    container_name: odoo
    depends_on:
      - db
    volumes:
      - /opt/odoo/config:/etc/odoo  # Monta la carpeta config del host a /etc/odoo en el contenedor
      - /opt/odoo/custom_modules:/mnt/extra-addons
      - /opt/odoo/oca_modules:/mnt/extra-addons # Esto monta el archivo de configuración desde el repositorio
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo
      - ADMIN_PASSWORD=admin
      - LOG_LEVEL=debug
    networks:
      - odoo_network

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - /opt/odoo/postgresql-data:/var/lib/postgresql/data
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge
